version: '3.7'

services:
  project:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../mlruns:../../mlruns
    environment:
      - MLFLOW_TRACKING_URI=file://../../mlruns
    working_dir: /app
    command: >
      mlserver start .